version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: ngodeyuk_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '2001:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4
    container_name: ngodeyuk_pg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "2002:80"
    depends_on:
      - postgres

  migrate:
    image: migrate/migrate
    container_name: ngodeyuk_migrate
    volumes:
      - ./database/migrations:/database/migrations
    depends_on:
      - postgres
    command: ["-path", "/database/migrations", "-database", "postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=${DB_SSL_MODE}", "up"]

volumes:
  postgres_data:

networks:
  new:
    driver: bridge

